sonar.projectKey=aje-reto-clientes
sonar.projectName=Reto clientes
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/**/*.test.js
sonar.exclusions=frontend/src/**/*.test.js,**/node_modules/**,**/.venv/**,**/dist/**,**/coverage/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
